import { config } from 'dotenv';
import { generateDirectusTypes } from 'directus-sdk-typegen';
import readlineSync from 'readline-sync';
import { readFileSync, writeFileSync } from 'fs';

config();

function postProcessTypes(outputPath: string): void {
	const disclaimer =
		'// @ts-nocheck\n/**\n * This file is auto-generated by the Directus type generator.\n * Do not edit this file manually. Regenerate types from Directus schema instead.\n */\n\n';
	let content = disclaimer + readFileSync(outputPath, 'utf-8');
	// Make FormSubmissionValue.id optional (generated as required, but should be optional for new submissions)
	content = content.replace(
		/(interface FormSubmissionValue \{[\s\S]*?\/\*\* @primaryKey \*\/\s*\n\s*)id: string/,
		'$1id?: string'
	);
	writeFileSync(outputPath, content, 'utf-8');
}

function promptForToken(): Promise<string> {
	if (!process.stdin.isTTY) {
		console.error('Cannot prompt for token: not a TTY. Set DIRECTUS_ADMIN_TOKEN env var instead.');
		process.exit(1);
	}
	const answer = readlineSync.question(
		'Enter your Directus admin token (with permissions to read system collections like directus_fields): ',
		{ hideEchoBack: true }
	);
	return Promise.resolve(answer.trim());
}

async function generateTypes() {
	const directusUrl = process.env.PUBLIC_DIRECTUS_URL;

	if (!directusUrl) {
		console.error('Error: PUBLIC_DIRECTUS_URL is missing in the .env file.');
		process.exit(1);
	}

	// Allow token to be provided via environment variable for testing/CI, otherwise prompt
	const directusToken = process.env.DIRECTUS_ADMIN_TOKEN || (await promptForToken());

	if (!directusToken) {
		console.error('Error: Admin token is required to generate types.');
		process.exit(1);
	}

	const outputPath = './src/lib/types/directus-schema.ts';

	try {
		await generateDirectusTypes({ outputPath, directusUrl, directusToken });
		postProcessTypes(outputPath);
		console.log('Types successfully generated!');
	} catch (error) {
		console.error('Failed to generate types:', error);
		process.exit(1);
	}
}

generateTypes();
